triage:
  label: triage
  dryRun: false

closeAndLock:
  labels:
    - label: 'ionitron: support'
      message: >
        Thanks for the issue! This issue appears to be a support request. We use this issue tracker exclusively for
        content issues, bug reports and feature requests related to the documentation. Please use our
        [forum](https://forum.ionicframework.com/) for help or questions about Ionic Framework.


        Thank you for using Ionic!
    - label: 'ionitron: missing template'
      message: >
        Thanks for the issue! It appears that you have not filled out the provided issue template. We use this issue
        template in order to gather more information and further assist you. Please create a new issue and ensure the
        template is fully filled out.


        Thank you for using Ionic!
  close: true
  lock: true
  dryRun: false

comment:
  labels:
    - label: "help wanted"
      message: >
        This issue has been labeled as `help wanted`. This label is added to issues
        that we believe would be good for contributors.


        If you'd like to work on this issue, please comment here letting us know that
        you would like to submit a pull request for it. This helps us to keep track of
        the pull request and make sure there isn't duplicated effort.


        For a guide on how to create a pull request and test this project locally to see
        your changes, see our [contributing documentation](https://github.com/ionic-team/ionic-docs/blob/main/CONTRIBUTING.md).


        Thank you!
    - label: 'ionitron: needs reproduction'
      message: >
        Thanks for the issue! This issue has been labeled as `needs reproduction`. This label is added to issues that
        we are not able to reproduce.


        Please provide easy to follow steps for us to reproduce this issue.
  dryRun: false

noReply:
  days: 14
  maxIssuesPerRun: 100
  label: "needs: reply"
  responseLabel: triage
  exemptProjects: true
  exemptMilestones: true
  message: >
    Thanks for the issue! This issue is being closed due to the lack of a reply. If this is still an issue,
    please create a new issue and ensure the template is fully filled out.


    Thank you for using Ionic!
  close: true
  lock: true
  dryRun: false

noReproduction:
  days: 14
  maxIssuesPerRun: 100
  label: "ionitron: needs reproduction"
  responseLabel: triage
  exemptProjects: true
  exemptMilestones: true
  message: >
    Thanks for the issue! This issue is being closed due to the lack of a reproduction. If this is still an issue,
    please create a new issue and ensure the template is fully filled out.


    Thank you for using Ionic!
  close: true
  lock: true
  dryRun: false
