files:
  - source: /src/assets/locales/en/messages.json
    translation: /src/assets/locales/%two_letters_code%/messages.json
  - source: /src/pages/**/*.md
    translation: /src/pages/%two_letters_code%/**/%original_file_name%
    ignore:
      - /src/pages/%two_letters_code%/**/%original_file_name%
