module.exports = {
 native: [
   {
     type: 'category',
     label: 'Getting Started',
     collapsed: false,
     items: [
       'index',
       'native-setup',
       'native-faq',
     ],
   },
   {
     type: 'category',
     label: 'Plugins',
     collapsed: false,
     items: [
       {
         type: 'autogenerated',
         dirName: 'native', // Generate section automatically based on files
       },
     ],
   },
 ],

}
