module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['index', 'intro/environment', 'intro/cli', 'intro/cdn', 'intro/vscode-extension', 'intro/next'],
    },
    {
      type: 'category',
      label: 'Upgrade Guides',
      collapsed: false,
      items: ['updating/8-0', 'updating/7-0', 'updating/6-0', 'updating/5-0', 'updating/4-0'],
    },
    {
      type: 'category',
      label: 'Developing',
      collapsed: false,
      items: [
        'developing/starting',
        'developing/previewing',
        'developing/scaffolding',
        'developing/ios',
        'developing/android',
        'developing/tips',
        'developing/hardware-back-button',
        'developing/keyboard',
        'developing/config',
        'developing/managing-focus',
      ],
    },
    {
      type: 'category',
      label: 'Layout',
      collapsed: false,
      items: [
        'layout/structure',
        {
          type: 'link',
          label: 'Responsive Grid',
          href: '/docs/api/grid',
        },
        'layout/global-stylesheets',
        'layout/css-utilities',
        'layout/dynamic-font-scaling',
      ],
    },
    {
      type: 'category',
      label: 'Theming',
      collapsed: false,
      items: [
        'theming/basics',
        'theming/platform-styles',
        'theming/css-variables',
        'theming/css-shadow-parts',
        'theming/colors',
        'theming/themes',
        'theming/dark-mode',
        'theming/high-contrast-mode',
        'theming/advanced',
        'theming/color-generator',
      ],
    },
    {
      type: 'category',
      label: 'Angular',
      collapsed: false,
      items: [
        'angular/overview',
        'angular/build-options',
        {
          type: 'category',
          label: 'Build Your First App',
          items: [
            'angular/your-first-app',
            'angular/your-first-app/taking-photos',
            'angular/your-first-app/saving-photos',
            'angular/your-first-app/loading-photos',
            'angular/your-first-app/adding-mobile',
            'angular/your-first-app/deploying-mobile',
            'angular/your-first-app/live-reload',
            'angular/your-first-app/distribute',
          ],
        },
        'angular/lifecycle',
        'angular/navigation',
        'angular/virtual-scroll',
        'angular/slides',
        'angular/platform',
        'angular/testing',
        'angular/storage',
        'angular/performance',
        'angular/pwa',
      ],
    },
    {
      type: 'category',
      label: 'React',
      collapsed: false,
      items: [
        'react',
        'react/quickstart',
        {
          type: 'category',
          label: 'Build Your First App',
          items: [
            'react/your-first-app',
            'react/your-first-app/taking-photos',
            'react/your-first-app/saving-photos',
            'react/your-first-app/loading-photos',
            'react/your-first-app/adding-mobile',
            'react/your-first-app/deploying-mobile',
            'react/your-first-app/live-reload',
            'react/your-first-app/distribute',
          ],
        },
        'react/adding-ionic-react-to-an-existing-react-project',
        'react/lifecycle',
        'react/navigation',
        'react/virtual-scroll',
        'react/slides',
        'react/platform',
        'react/pwa',
        'react/overlays',
        'react/storage',
        {
          type: 'category',
          label: 'Testing',
          items: [
            'react/testing/introduction',
            {
              type: 'category',
              label: 'Unit Testing',
              collapsed: false,
              items: [
                'react/testing/unit-testing/setup',
                'react/testing/unit-testing/examples',
                'react/testing/unit-testing/best-practices',
              ],
            },
          ],
        },
        'react/performance',
      ],
    },
    {
      type: 'category',
      label: 'Vue',
      collapsed: false,
      items: [
        'vue/overview',
        'vue/quickstart',
        {
          type: 'category',
          label: 'Build Your First App',
          items: [
            'vue/your-first-app',
            'vue/your-first-app/taking-photos',
            'vue/your-first-app/saving-photos',
            'vue/your-first-app/loading-photos',
            'vue/your-first-app/adding-mobile',
            'vue/your-first-app/deploying-mobile',
            'vue/your-first-app/live-reload',
            'vue/your-first-app/distribute',
          ],
        },
        'vue/lifecycle',
        'vue/navigation',
        'vue/virtual-scroll',
        'vue/slides',
        'vue/utility-functions',
        'vue/platform',
        'vue/pwa',
        'vue/storage',
        'vue/testing',
        'vue/troubleshooting',
        'vue/performance',
      ],
    },
    {
      type: 'category',
      label: 'Utilities',
      collapsed: false,
      items: ['utilities/animations', 'utilities/gestures'],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsed: false,
      items: ['deployment/app-store', 'deployment/play-store', 'deployment/progressive-web-app'],
    },
    {
      type: 'category',
      label: 'Techniques',
      collapsed: false,
      items: ['techniques/security'],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: false,
      items: [
        'troubleshooting/debugging',
        'troubleshooting/build',
        'troubleshooting/runtime',
        'troubleshooting/native',
        'troubleshooting/cors',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: [
        'core-concepts/fundamentals',
        'core-concepts/cross-platform',
        'core-concepts/webview',
        'core-concepts/what-are-progressive-web-apps',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: false,
      items: ['contributing/how-to-contribute', 'contributing/coc'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/glossary',
        'reference/versioning',
        'reference/release-notes',
        {
          type: 'link',
          label: 'GitHub Changelog',
          href: 'https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md',
        },
        'reference/support',
        'reference/browser-support',
      ],
    },
  ],

  api: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['components'],
    },
    {
      type: 'category',
      label: 'Action Sheet',
      collapsed: false,
      items: ['api/action-sheet'],
    },
    {
      type: 'category',
      label: 'Accordion',
      collapsed: false,
      items: ['api/accordion', 'api/accordion-group'],
    },
    {
      type: 'category',
      label: 'Alert',
      collapsed: false,
      items: ['api/alert'],
    },
    {
      type: 'category',
      label: 'Badge',
      collapsed: false,
      items: ['api/badge'],
    },
    {
      type: 'category',
      label: 'Breadcrumb',
      collapsed: false,
      items: ['api/breadcrumb', 'api/breadcrumbs'],
    },
    {
      type: 'category',
      label: 'Button',
      collapsed: false,
      items: ['api/button', 'api/ripple-effect'],
    },
    {
      type: 'category',
      label: 'Card',
      collapsed: false,
      items: ['api/card', 'api/card-content', 'api/card-header', 'api/card-subtitle', 'api/card-title'],
    },
    {
      type: 'category',
      label: 'Checkbox',
      collapsed: false,
      items: ['api/checkbox'],
    },
    {
      type: 'category',
      label: 'Chip',
      collapsed: false,
      items: ['api/chip'],
    },
    {
      type: 'category',
      label: 'Content',
      collapsed: false,
      items: ['api/app', 'api/content'],
    },
    {
      type: 'category',
      label: 'Date & Time Pickers',
      collapsed: false,
      items: [
        'api/datetime',
        'api/datetime-button',
        'api/picker',
        'api/picker-column',
        'api/picker-column-option',
        'api/picker-legacy',
      ],
    },
    {
      type: 'category',
      label: 'Floating Action Button',
      collapsed: false,
      items: ['api/fab', 'api/fab-button', 'api/fab-list'],
    },
    {
      type: 'category',
      label: 'Grid',
      collapsed: false,
      items: ['api/grid', 'api/col', 'api/row'],
    },
    {
      type: 'category',
      label: 'Infinite Scroll',
      collapsed: false,
      items: ['api/infinite-scroll', 'api/infinite-scroll-content'],
    },
    {
      type: 'category',
      label: 'Icons',
      collapsed: false,
      items: ['api/icon'],
    },
    {
      type: 'category',
      label: 'Input',
      collapsed: false,
      items: ['api/input', 'api/input-password-toggle', 'api/textarea'],
    },
    {
      type: 'category',
      label: 'Item',
      collapsed: false,
      items: [
        'api/item',
        'api/item-divider',
        'api/item-group',
        'api/item-sliding',
        'api/item-options',
        'api/item-option',
        'api/label',
        'api/note',
      ],
    },
    {
      type: 'category',
      label: 'List',
      collapsed: false,
      items: ['api/list', 'api/list-header'],
    },
    {
      type: 'category',
      label: 'Media',
      collapsed: false,
      items: ['api/avatar', 'api/icon', 'api/img', 'api/thumbnail'],
    },
    {
      type: 'category',
      label: 'Menu',
      collapsed: false,
      items: ['api/menu', 'api/menu-button', 'api/menu-toggle', 'api/split-pane'],
    },
    {
      type: 'category',
      label: 'Modal',
      collapsed: false,
      items: ['api/modal', 'api/backdrop'],
    },
    {
      type: 'category',
      label: 'Navigation',
      collapsed: false,
      items: ['api/nav', 'api/nav-link'],
    },
    {
      type: 'category',
      label: 'Popover',
      collapsed: false,
      items: ['api/popover'],
    },
    {
      type: 'category',
      label: 'Progress Indicators',
      collapsed: false,
      items: ['api/loading', 'api/progress-bar', 'api/skeleton-text', 'api/spinner'],
    },
    {
      type: 'category',
      label: 'Radio',
      collapsed: false,
      items: ['api/radio', 'api/radio-group'],
    },
    {
      type: 'category',
      label: 'Range',
      collapsed: false,
      items: ['api/range'],
    },
    {
      type: 'category',
      label: 'Refresher',
      collapsed: false,
      items: ['api/refresher', 'api/refresher-content'],
    },
    {
      type: 'category',
      label: 'Reorder',
      collapsed: false,
      items: ['api/reorder', 'api/reorder-group'],
    },
    {
      type: 'category',
      label: 'Routing',
      collapsed: false,
      items: ['api/router', 'api/router-link', 'api/router-outlet', 'api/route', 'api/route-redirect'],
    },
    {
      type: 'category',
      label: 'Searchbar',
      collapsed: false,
      items: ['api/searchbar'],
    },
    {
      type: 'category',
      label: 'Segment',
      collapsed: false,
      items: ['api/segment', 'api/segment-button'],
    },
    {
      type: 'category',
      label: 'Select',
      collapsed: false,
      items: ['api/select', 'api/select-option'],
    },
    {
      type: 'category',
      label: 'Tabs',
      collapsed: false,
      items: ['api/tabs', 'api/tab', 'api/tab-bar', 'api/tab-button'],
    },
    {
      type: 'category',
      label: 'Toast',
      collapsed: false,
      items: ['api/toast'],
    },
    {
      type: 'category',
      label: 'Toggle',
      collapsed: false,
      items: ['api/toggle'],
    },
    {
      type: 'category',
      label: 'Toolbar',
      collapsed: false,
      items: ['api/toolbar', 'api/header', 'api/footer', 'api/title', 'api/buttons', 'api/back-button'],
    },
    {
      type: 'category',
      label: 'Typography',
      collapsed: false,
      items: ['api/text'],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: ['api'],
    },
  ],

  cli: [
    {
      type: 'category',
      label: 'CLI Documentation',
      collapsed: false,
      items: [
        'cli',
        'cli/configuration',
        'cli/livereload',
        'cli/using-a-proxy',
        {
          type: 'link',
          label: 'Changelog',
          href: 'https://github.com/ionic-team/ionic-cli/blob/develop/packages/@ionic/cli/CHANGELOG.md',
        },
      ],
    },
    {
      type: 'category',
      label: 'Command Reference',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli/commands', // Generate section automatically based on files
        },
      ],
    },
  ],

  native: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['native', 'native-setup', 'native-faq'],
    },
    {
      type: 'category',
      label: 'Plugins',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'native', // Generate section automatically based on files
        },
      ],
    },
  ],
};
