module.exports = {
  native: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'index',
        'setup',
        'faq',
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'plugins', // Generate section automatically based on files
        },
      ],
    },
  ],
};
