/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface PageActionSheet {}
  interface PageActionSheetAttributes extends StencilHTMLAttributes {}

  interface PageAlert {}
  interface PageAlertAttributes extends StencilHTMLAttributes {}

  interface PageBadge {}
  interface PageBadgeAttributes extends StencilHTMLAttributes {}

  interface PageButton {}
  interface PageButtonAttributes extends StencilHTMLAttributes {}

  interface PageCard {}
  interface PageCardAttributes extends StencilHTMLAttributes {}

  interface PageCheckbox {}
  interface PageCheckboxAttributes extends StencilHTMLAttributes {}

  interface ComponentPreview {}
  interface ComponentPreviewAttributes extends StencilHTMLAttributes {}

  interface PageDatetime {}
  interface PageDatetimeAttributes extends StencilHTMLAttributes {}

  interface PageFab {}
  interface PageFabAttributes extends StencilHTMLAttributes {}

  interface PageGrid {}
  interface PageGridAttributes extends StencilHTMLAttributes {}

  interface AppList {
    'items': any[];
  }
  interface AppListAttributes extends StencilHTMLAttributes {
    'items'?: any[];
  }

  interface PageInfiniteScroll {}
  interface PageInfiniteScrollAttributes extends StencilHTMLAttributes {}

  interface PageInput {}
  interface PageInputAttributes extends StencilHTMLAttributes {}

  interface PageList {}
  interface PageListAttributes extends StencilHTMLAttributes {}

  interface PageLoading {}
  interface PageLoadingAttributes extends StencilHTMLAttributes {}

  interface HomePage {}
  interface HomePageAttributes extends StencilHTMLAttributes {}

  interface PageMenu {}
  interface PageMenuAttributes extends StencilHTMLAttributes {}

  interface ProfilePage {}
  interface ProfilePageAttributes extends StencilHTMLAttributes {}

  interface ModalPage {
    'char': string;
  }
  interface ModalPageAttributes extends StencilHTMLAttributes {
    'char'?: string;
  }

  interface PageModal {}
  interface PageModalAttributes extends StencilHTMLAttributes {}

  interface NavDetails {
    'tech': any;
  }
  interface NavDetailsAttributes extends StencilHTMLAttributes {
    'tech'?: any;
  }

  interface NavHome {}
  interface NavHomeAttributes extends StencilHTMLAttributes {}

  interface PageNav {}
  interface PageNavAttributes extends StencilHTMLAttributes {}

  interface PageIndex {
    'pages': any[];
  }
  interface PageIndexAttributes extends StencilHTMLAttributes {
    'pages'?: any[];
  }

  interface PopoverPage {
    'contentEl': HTMLElement;
  }
  interface PopoverPageAttributes extends StencilHTMLAttributes {
    'contentEl'?: HTMLElement;
  }

  interface PagePopover {}
  interface PagePopoverAttributes extends StencilHTMLAttributes {}

  interface PageRange {}
  interface PageRangeAttributes extends StencilHTMLAttributes {}

  interface PageRefresher {}
  interface PageRefresherAttributes extends StencilHTMLAttributes {}

  interface PageSearchbar {}
  interface PageSearchbarAttributes extends StencilHTMLAttributes {}

  interface PageSelect {}
  interface PageSelectAttributes extends StencilHTMLAttributes {}

  interface PageSlides {}
  interface PageSlidesAttributes extends StencilHTMLAttributes {}

  interface PageSpinner {}
  interface PageSpinnerAttributes extends StencilHTMLAttributes {}

  interface PageTabs {}
  interface PageTabsAttributes extends StencilHTMLAttributes {}

  interface PageToast {}
  interface PageToastAttributes extends StencilHTMLAttributes {}

  interface PageVirtualScroll {}
  interface PageVirtualScrollAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PageActionSheet': Components.PageActionSheet;
    'PageAlert': Components.PageAlert;
    'PageBadge': Components.PageBadge;
    'PageButton': Components.PageButton;
    'PageCard': Components.PageCard;
    'PageCheckbox': Components.PageCheckbox;
    'ComponentPreview': Components.ComponentPreview;
    'PageDatetime': Components.PageDatetime;
    'PageFab': Components.PageFab;
    'PageGrid': Components.PageGrid;
    'AppList': Components.AppList;
    'PageInfiniteScroll': Components.PageInfiniteScroll;
    'PageInput': Components.PageInput;
    'PageList': Components.PageList;
    'PageLoading': Components.PageLoading;
    'HomePage': Components.HomePage;
    'PageMenu': Components.PageMenu;
    'ProfilePage': Components.ProfilePage;
    'ModalPage': Components.ModalPage;
    'PageModal': Components.PageModal;
    'NavDetails': Components.NavDetails;
    'NavHome': Components.NavHome;
    'PageNav': Components.PageNav;
    'PageIndex': Components.PageIndex;
    'PopoverPage': Components.PopoverPage;
    'PagePopover': Components.PagePopover;
    'PageRange': Components.PageRange;
    'PageRefresher': Components.PageRefresher;
    'PageSearchbar': Components.PageSearchbar;
    'PageSelect': Components.PageSelect;
    'PageSlides': Components.PageSlides;
    'PageSpinner': Components.PageSpinner;
    'PageTabs': Components.PageTabs;
    'PageToast': Components.PageToast;
    'PageVirtualScroll': Components.PageVirtualScroll;
  }

  interface StencilIntrinsicElements {
    'page-action-sheet': Components.PageActionSheetAttributes;
    'page-alert': Components.PageAlertAttributes;
    'page-badge': Components.PageBadgeAttributes;
    'page-button': Components.PageButtonAttributes;
    'page-card': Components.PageCardAttributes;
    'page-checkbox': Components.PageCheckboxAttributes;
    'component-preview': Components.ComponentPreviewAttributes;
    'page-datetime': Components.PageDatetimeAttributes;
    'page-fab': Components.PageFabAttributes;
    'page-grid': Components.PageGridAttributes;
    'app-list': Components.AppListAttributes;
    'page-infinite-scroll': Components.PageInfiniteScrollAttributes;
    'page-input': Components.PageInputAttributes;
    'page-list': Components.PageListAttributes;
    'page-loading': Components.PageLoadingAttributes;
    'home-page': Components.HomePageAttributes;
    'page-menu': Components.PageMenuAttributes;
    'profile-page': Components.ProfilePageAttributes;
    'modal-page': Components.ModalPageAttributes;
    'page-modal': Components.PageModalAttributes;
    'nav-details': Components.NavDetailsAttributes;
    'nav-home': Components.NavHomeAttributes;
    'page-nav': Components.PageNavAttributes;
    'page-index': Components.PageIndexAttributes;
    'popover-page': Components.PopoverPageAttributes;
    'page-popover': Components.PagePopoverAttributes;
    'page-range': Components.PageRangeAttributes;
    'page-refresher': Components.PageRefresherAttributes;
    'page-searchbar': Components.PageSearchbarAttributes;
    'page-select': Components.PageSelectAttributes;
    'page-slides': Components.PageSlidesAttributes;
    'page-spinner': Components.PageSpinnerAttributes;
    'page-tabs': Components.PageTabsAttributes;
    'page-toast': Components.PageToastAttributes;
    'page-virtual-scroll': Components.PageVirtualScrollAttributes;
  }


  interface HTMLPageActionSheetElement extends Components.PageActionSheet, HTMLStencilElement {}
  var HTMLPageActionSheetElement: {
    prototype: HTMLPageActionSheetElement;
    new (): HTMLPageActionSheetElement;
  };

  interface HTMLPageAlertElement extends Components.PageAlert, HTMLStencilElement {}
  var HTMLPageAlertElement: {
    prototype: HTMLPageAlertElement;
    new (): HTMLPageAlertElement;
  };

  interface HTMLPageBadgeElement extends Components.PageBadge, HTMLStencilElement {}
  var HTMLPageBadgeElement: {
    prototype: HTMLPageBadgeElement;
    new (): HTMLPageBadgeElement;
  };

  interface HTMLPageButtonElement extends Components.PageButton, HTMLStencilElement {}
  var HTMLPageButtonElement: {
    prototype: HTMLPageButtonElement;
    new (): HTMLPageButtonElement;
  };

  interface HTMLPageCardElement extends Components.PageCard, HTMLStencilElement {}
  var HTMLPageCardElement: {
    prototype: HTMLPageCardElement;
    new (): HTMLPageCardElement;
  };

  interface HTMLPageCheckboxElement extends Components.PageCheckbox, HTMLStencilElement {}
  var HTMLPageCheckboxElement: {
    prototype: HTMLPageCheckboxElement;
    new (): HTMLPageCheckboxElement;
  };

  interface HTMLComponentPreviewElement extends Components.ComponentPreview, HTMLStencilElement {}
  var HTMLComponentPreviewElement: {
    prototype: HTMLComponentPreviewElement;
    new (): HTMLComponentPreviewElement;
  };

  interface HTMLPageDatetimeElement extends Components.PageDatetime, HTMLStencilElement {}
  var HTMLPageDatetimeElement: {
    prototype: HTMLPageDatetimeElement;
    new (): HTMLPageDatetimeElement;
  };

  interface HTMLPageFabElement extends Components.PageFab, HTMLStencilElement {}
  var HTMLPageFabElement: {
    prototype: HTMLPageFabElement;
    new (): HTMLPageFabElement;
  };

  interface HTMLPageGridElement extends Components.PageGrid, HTMLStencilElement {}
  var HTMLPageGridElement: {
    prototype: HTMLPageGridElement;
    new (): HTMLPageGridElement;
  };

  interface HTMLAppListElement extends Components.AppList, HTMLStencilElement {}
  var HTMLAppListElement: {
    prototype: HTMLAppListElement;
    new (): HTMLAppListElement;
  };

  interface HTMLPageInfiniteScrollElement extends Components.PageInfiniteScroll, HTMLStencilElement {}
  var HTMLPageInfiniteScrollElement: {
    prototype: HTMLPageInfiniteScrollElement;
    new (): HTMLPageInfiniteScrollElement;
  };

  interface HTMLPageInputElement extends Components.PageInput, HTMLStencilElement {}
  var HTMLPageInputElement: {
    prototype: HTMLPageInputElement;
    new (): HTMLPageInputElement;
  };

  interface HTMLPageListElement extends Components.PageList, HTMLStencilElement {}
  var HTMLPageListElement: {
    prototype: HTMLPageListElement;
    new (): HTMLPageListElement;
  };

  interface HTMLPageLoadingElement extends Components.PageLoading, HTMLStencilElement {}
  var HTMLPageLoadingElement: {
    prototype: HTMLPageLoadingElement;
    new (): HTMLPageLoadingElement;
  };

  interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {}
  var HTMLHomePageElement: {
    prototype: HTMLHomePageElement;
    new (): HTMLHomePageElement;
  };

  interface HTMLPageMenuElement extends Components.PageMenu, HTMLStencilElement {}
  var HTMLPageMenuElement: {
    prototype: HTMLPageMenuElement;
    new (): HTMLPageMenuElement;
  };

  interface HTMLProfilePageElement extends Components.ProfilePage, HTMLStencilElement {}
  var HTMLProfilePageElement: {
    prototype: HTMLProfilePageElement;
    new (): HTMLProfilePageElement;
  };

  interface HTMLModalPageElement extends Components.ModalPage, HTMLStencilElement {}
  var HTMLModalPageElement: {
    prototype: HTMLModalPageElement;
    new (): HTMLModalPageElement;
  };

  interface HTMLPageModalElement extends Components.PageModal, HTMLStencilElement {}
  var HTMLPageModalElement: {
    prototype: HTMLPageModalElement;
    new (): HTMLPageModalElement;
  };

  interface HTMLNavDetailsElement extends Components.NavDetails, HTMLStencilElement {}
  var HTMLNavDetailsElement: {
    prototype: HTMLNavDetailsElement;
    new (): HTMLNavDetailsElement;
  };

  interface HTMLNavHomeElement extends Components.NavHome, HTMLStencilElement {}
  var HTMLNavHomeElement: {
    prototype: HTMLNavHomeElement;
    new (): HTMLNavHomeElement;
  };

  interface HTMLPageNavElement extends Components.PageNav, HTMLStencilElement {}
  var HTMLPageNavElement: {
    prototype: HTMLPageNavElement;
    new (): HTMLPageNavElement;
  };

  interface HTMLPageIndexElement extends Components.PageIndex, HTMLStencilElement {}
  var HTMLPageIndexElement: {
    prototype: HTMLPageIndexElement;
    new (): HTMLPageIndexElement;
  };

  interface HTMLPopoverPageElement extends Components.PopoverPage, HTMLStencilElement {}
  var HTMLPopoverPageElement: {
    prototype: HTMLPopoverPageElement;
    new (): HTMLPopoverPageElement;
  };

  interface HTMLPagePopoverElement extends Components.PagePopover, HTMLStencilElement {}
  var HTMLPagePopoverElement: {
    prototype: HTMLPagePopoverElement;
    new (): HTMLPagePopoverElement;
  };

  interface HTMLPageRangeElement extends Components.PageRange, HTMLStencilElement {}
  var HTMLPageRangeElement: {
    prototype: HTMLPageRangeElement;
    new (): HTMLPageRangeElement;
  };

  interface HTMLPageRefresherElement extends Components.PageRefresher, HTMLStencilElement {}
  var HTMLPageRefresherElement: {
    prototype: HTMLPageRefresherElement;
    new (): HTMLPageRefresherElement;
  };

  interface HTMLPageSearchbarElement extends Components.PageSearchbar, HTMLStencilElement {}
  var HTMLPageSearchbarElement: {
    prototype: HTMLPageSearchbarElement;
    new (): HTMLPageSearchbarElement;
  };

  interface HTMLPageSelectElement extends Components.PageSelect, HTMLStencilElement {}
  var HTMLPageSelectElement: {
    prototype: HTMLPageSelectElement;
    new (): HTMLPageSelectElement;
  };

  interface HTMLPageSlidesElement extends Components.PageSlides, HTMLStencilElement {}
  var HTMLPageSlidesElement: {
    prototype: HTMLPageSlidesElement;
    new (): HTMLPageSlidesElement;
  };

  interface HTMLPageSpinnerElement extends Components.PageSpinner, HTMLStencilElement {}
  var HTMLPageSpinnerElement: {
    prototype: HTMLPageSpinnerElement;
    new (): HTMLPageSpinnerElement;
  };

  interface HTMLPageTabsElement extends Components.PageTabs, HTMLStencilElement {}
  var HTMLPageTabsElement: {
    prototype: HTMLPageTabsElement;
    new (): HTMLPageTabsElement;
  };

  interface HTMLPageToastElement extends Components.PageToast, HTMLStencilElement {}
  var HTMLPageToastElement: {
    prototype: HTMLPageToastElement;
    new (): HTMLPageToastElement;
  };

  interface HTMLPageVirtualScrollElement extends Components.PageVirtualScroll, HTMLStencilElement {}
  var HTMLPageVirtualScrollElement: {
    prototype: HTMLPageVirtualScrollElement;
    new (): HTMLPageVirtualScrollElement;
  };

  interface HTMLElementTagNameMap {
    'page-action-sheet': HTMLPageActionSheetElement
    'page-alert': HTMLPageAlertElement
    'page-badge': HTMLPageBadgeElement
    'page-button': HTMLPageButtonElement
    'page-card': HTMLPageCardElement
    'page-checkbox': HTMLPageCheckboxElement
    'component-preview': HTMLComponentPreviewElement
    'page-datetime': HTMLPageDatetimeElement
    'page-fab': HTMLPageFabElement
    'page-grid': HTMLPageGridElement
    'app-list': HTMLAppListElement
    'page-infinite-scroll': HTMLPageInfiniteScrollElement
    'page-input': HTMLPageInputElement
    'page-list': HTMLPageListElement
    'page-loading': HTMLPageLoadingElement
    'home-page': HTMLHomePageElement
    'page-menu': HTMLPageMenuElement
    'profile-page': HTMLProfilePageElement
    'modal-page': HTMLModalPageElement
    'page-modal': HTMLPageModalElement
    'nav-details': HTMLNavDetailsElement
    'nav-home': HTMLNavHomeElement
    'page-nav': HTMLPageNavElement
    'page-index': HTMLPageIndexElement
    'popover-page': HTMLPopoverPageElement
    'page-popover': HTMLPagePopoverElement
    'page-range': HTMLPageRangeElement
    'page-refresher': HTMLPageRefresherElement
    'page-searchbar': HTMLPageSearchbarElement
    'page-select': HTMLPageSelectElement
    'page-slides': HTMLPageSlidesElement
    'page-spinner': HTMLPageSpinnerElement
    'page-tabs': HTMLPageTabsElement
    'page-toast': HTMLPageToastElement
    'page-virtual-scroll': HTMLPageVirtualScrollElement
  }

  interface ElementTagNameMap {
    'page-action-sheet': HTMLPageActionSheetElement;
    'page-alert': HTMLPageAlertElement;
    'page-badge': HTMLPageBadgeElement;
    'page-button': HTMLPageButtonElement;
    'page-card': HTMLPageCardElement;
    'page-checkbox': HTMLPageCheckboxElement;
    'component-preview': HTMLComponentPreviewElement;
    'page-datetime': HTMLPageDatetimeElement;
    'page-fab': HTMLPageFabElement;
    'page-grid': HTMLPageGridElement;
    'app-list': HTMLAppListElement;
    'page-infinite-scroll': HTMLPageInfiniteScrollElement;
    'page-input': HTMLPageInputElement;
    'page-list': HTMLPageListElement;
    'page-loading': HTMLPageLoadingElement;
    'home-page': HTMLHomePageElement;
    'page-menu': HTMLPageMenuElement;
    'profile-page': HTMLProfilePageElement;
    'modal-page': HTMLModalPageElement;
    'page-modal': HTMLPageModalElement;
    'nav-details': HTMLNavDetailsElement;
    'nav-home': HTMLNavHomeElement;
    'page-nav': HTMLPageNavElement;
    'page-index': HTMLPageIndexElement;
    'popover-page': HTMLPopoverPageElement;
    'page-popover': HTMLPagePopoverElement;
    'page-range': HTMLPageRangeElement;
    'page-refresher': HTMLPageRefresherElement;
    'page-searchbar': HTMLPageSearchbarElement;
    'page-select': HTMLPageSelectElement;
    'page-slides': HTMLPageSlidesElement;
    'page-spinner': HTMLPageSpinnerElement;
    'page-tabs': HTMLPageTabsElement;
    'page-toast': HTMLPageToastElement;
    'page-virtual-scroll': HTMLPageVirtualScrollElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
