/* tslint:disable */

export const commandMenu = {
  "build": "/docs/cli/commands/build",
  "capacitor add": "/docs/cli/commands/capacitor-add",
  "capacitor copy": "/docs/cli/commands/capacitor-copy",
  "capacitor open": "/docs/cli/commands/capacitor-open",
  "capacitor run": "/docs/cli/commands/capacitor-run",
  "capacitor sync": "/docs/cli/commands/capacitor-sync",
  "capacitor update": "/docs/cli/commands/capacitor-update",
  "config get": "/docs/cli/commands/config-get",
  "config set": "/docs/cli/commands/config-set",
  "config unset": "/docs/cli/commands/config-unset",
  "cordova build": "/docs/cli/commands/cordova-build",
  "cordova compile": "/docs/cli/commands/cordova-compile",
  "cordova emulate": "/docs/cli/commands/cordova-emulate",
  "cordova platform": "/docs/cli/commands/cordova-platform",
  "cordova plugin": "/docs/cli/commands/cordova-plugin",
  "cordova prepare": "/docs/cli/commands/cordova-prepare",
  "cordova requirements": "/docs/cli/commands/cordova-requirements",
  "cordova resources": "/docs/cli/commands/cordova-resources",
  "cordova run": "/docs/cli/commands/cordova-run",
  "docs": "/docs/cli/commands/docs",
  "doctor check": "/docs/cli/commands/doctor-check",
  "doctor list": "/docs/cli/commands/doctor-list",
  "doctor treat": "/docs/cli/commands/doctor-treat",
  "generate": "/docs/cli/commands/generate",
  "git remote": "/docs/cli/commands/git-remote",
  "info": "/docs/cli/commands/info",
  "init": "/docs/cli/commands/init",
  "integrations disable": "/docs/cli/commands/integrations-disable",
  "integrations enable": "/docs/cli/commands/integrations-enable",
  "integrations list": "/docs/cli/commands/integrations-list",
  "link": "/docs/cli/commands/link",
  "login": "/docs/cli/commands/login",
  "logout": "/docs/cli/commands/logout",
  "repair": "/docs/cli/commands/repair",
  "serve": "/docs/cli/commands/serve",
  "signup": "/docs/cli/commands/signup",
  "ssh add": "/docs/cli/commands/ssh-add",
  "ssh delete": "/docs/cli/commands/ssh-delete",
  "ssh generate": "/docs/cli/commands/ssh-generate",
  "ssh list": "/docs/cli/commands/ssh-list",
  "ssh setup": "/docs/cli/commands/ssh-setup",
  "ssh use": "/docs/cli/commands/ssh-use",
  "ssl generate": "/docs/cli/commands/ssl-generate",
  "start": "/docs/cli/commands/start"
};
