/* tslint:disable */

export const commandMenu = {
  "build": "/docs/cli/build",
  "capacitor add": "/docs/cli/capacitor-add",
  "capacitor copy": "/docs/cli/capacitor-copy",
  "capacitor open": "/docs/cli/capacitor-open",
  "capacitor run": "/docs/cli/capacitor-run",
  "capacitor sync": "/docs/cli/capacitor-sync",
  "capacitor update": "/docs/cli/capacitor-update",
  "config get": "/docs/cli/config-get",
  "config set": "/docs/cli/config-set",
  "config unset": "/docs/cli/config-unset",
  "cordova build": "/docs/cli/cordova-build",
  "cordova compile": "/docs/cli/cordova-compile",
  "cordova emulate": "/docs/cli/cordova-emulate",
  "cordova platform": "/docs/cli/cordova-platform",
  "cordova plugin": "/docs/cli/cordova-plugin",
  "cordova prepare": "/docs/cli/cordova-prepare",
  "cordova requirements": "/docs/cli/cordova-requirements",
  "cordova resources": "/docs/cli/cordova-resources",
  "cordova run": "/docs/cli/cordova-run",
  "docs": "/docs/cli/docs",
  "doctor check": "/docs/cli/doctor-check",
  "doctor list": "/docs/cli/doctor-list",
  "doctor treat": "/docs/cli/doctor-treat",
  "git remote": "/docs/cli/git-remote",
  "info": "/docs/cli/info",
  "integrations disable": "/docs/cli/integrations-disable",
  "integrations enable": "/docs/cli/integrations-enable",
  "integrations list": "/docs/cli/integrations-list",
  "link": "/docs/cli/link",
  "login": "/docs/cli/login",
  "logout": "/docs/cli/logout",
  "repair": "/docs/cli/repair",
  "serve": "/docs/cli/serve",
  "signup": "/docs/cli/signup",
  "ssh add": "/docs/cli/ssh-add",
  "ssh delete": "/docs/cli/ssh-delete",
  "ssh generate": "/docs/cli/ssh-generate",
  "ssh list": "/docs/cli/ssh-list",
  "ssh setup": "/docs/cli/ssh-setup",
  "ssh use": "/docs/cli/ssh-use",
  "ssl generate": "/docs/cli/ssl-generate",
  "start": "/docs/cli/start"
};
