/* tslint:disable */

export const cliMenu = {
  "Overview": "/docs/cli/overview",
  "Build": "/docs/cli/build",
  "Capacitor Add": "/docs/cli/capacitor-add",
  "Capacitor Copy": "/docs/cli/capacitor-copy",
  "Capacitor Open": "/docs/cli/capacitor-open",
  "Capacitor Run": "/docs/cli/capacitor-run",
  "Capacitor Sync": "/docs/cli/capacitor-sync",
  "Capacitor Update": "/docs/cli/capacitor-update",
  "Config Get": "/docs/cli/config-get",
  "Config Set": "/docs/cli/config-set",
  "Config Unset": "/docs/cli/config-unset",
  "Cordova Build": "/docs/cli/cordova-build",
  "Cordova Compile": "/docs/cli/cordova-compile",
  "Cordova Emulate": "/docs/cli/cordova-emulate",
  "Cordova Platform": "/docs/cli/cordova-platform",
  "Cordova Plugin": "/docs/cli/cordova-plugin",
  "Cordova Prepare": "/docs/cli/cordova-prepare",
  "Cordova Requirements": "/docs/cli/cordova-requirements",
  "Cordova Resources": "/docs/cli/cordova-resources",
  "Cordova Run": "/docs/cli/cordova-run",
  "Docs": "/docs/cli/docs",
  "Doctor Check": "/docs/cli/doctor-check",
  "Doctor List": "/docs/cli/doctor-list",
  "Doctor Treat": "/docs/cli/doctor-treat",
  "Git Remote": "/docs/cli/git-remote",
  "Info": "/docs/cli/info",
  "Integrations Disable": "/docs/cli/integrations-disable",
  "Integrations Enable": "/docs/cli/integrations-enable",
  "Integrations List": "/docs/cli/integrations-list",
  "Link": "/docs/cli/link",
  "Login": "/docs/cli/login",
  "Logout": "/docs/cli/logout",
  "Repair": "/docs/cli/repair",
  "Serve": "/docs/cli/serve",
  "Signup": "/docs/cli/signup",
  "Ssh Add": "/docs/cli/ssh-add",
  "Ssh Delete": "/docs/cli/ssh-delete",
  "Ssh Generate": "/docs/cli/ssh-generate",
  "Ssh List": "/docs/cli/ssh-list",
  "Ssh Setup": "/docs/cli/ssh-setup",
  "Ssh Use": "/docs/cli/ssh-use",
  "Ssl Generate": "/docs/cli/ssl-generate",
  "Start": "/docs/cli/start"
};
