export const main = {
  'Home': '/docs',
  'Introduction': {
    'What is Ionic Framework': '/docs/intro',
    'Core Concepts': '/docs/intro/concepts',
    'Browser Support': '/docs/intro/browser-support',
    'Versioning': '/docs/intro/versioning',
    'Support': '/docs/intro/support'
  },
  'Installation': {
    'CLI Installation':  '/docs/installation/cli',
    'Packages & CDN': '/docs/installation/cdn',
    'Environment Setup': '/docs/installation/environment',
    'iOS Setup': '/docs/installation/ios',
    'Android Setup': '/docs/installation/android',
  },
  'Building': {
    'Starting': '/docs/building/starting',
    'Scaffolding': '/docs/building/scaffolding',
    'Migration': '/docs/building/migration',
    'Cross Platform': '/docs/building/cross-platform',
    'Running Overview': '/docs/building/running',
    'Running on iOS': '/docs/building/ios',
    'Running on Android': '/docs/building/android',
    'Testing': '/docs/building/testing',
    'Contributing': '/docs/building/contributing',
    'Web View': '/docs/building/webview',
    'Ionic Storage': '/docs/building/storage'
  },
  'Components': {
    'Overview': '/docs/components/overview',
    "action-sheet": "/docs/components/action-sheet",
    "alert": "/docs/components/alert",
    "anchor": "/docs/components/anchor",
    "app": "/docs/components/app",
    "avatar": "/docs/components/avatar",
    "back-button": "/docs/components/back-button",
    "backdrop": "/docs/components/backdrop",
    "badge": "/docs/components/badge",
    "button": "/docs/components/button",
    "buttons": "/docs/components/buttons",
    "card": "/docs/components/card",
    "card-content": "/docs/components/card-content",
    "card-header": "/docs/components/card-header",
    "card-subtitle": "/docs/components/card-subtitle",
    "card-title": "/docs/components/card-title",
    "checkbox": "/docs/components/checkbox",
    "chip": "/docs/components/chip",
    "chip-button": "/docs/components/chip-button",
    "col": "/docs/components/col",
    "content": "/docs/components/content",
    "datetime": "/docs/components/datetime",
    "fab": "/docs/components/fab",
    "fab-button": "/docs/components/fab-button",
    "fab-list": "/docs/components/fab-list",
    "footer": "/docs/components/footer",
    "gesture": "/docs/components/gesture",
    "grid": "/docs/components/grid",
    "header": "/docs/components/header",
    "hide-when": "/docs/components/hide-when",
    "infinite-scroll": "/docs/components/infinite-scroll",
    "infinite-scroll-content": "/docs/components/infinite-scroll-content",
    "input": "/docs/components/input",
    "item": "/docs/components/item",
    "item-divider": "/docs/components/item-divider",
    "item-group": "/docs/components/item-group",
    "item-option": "/docs/components/item-option",
    "item-options": "/docs/components/item-options",
    "item-sliding": "/docs/components/item-sliding",
    "label": "/docs/components/label",
    "list": "/docs/components/list",
    "list-header": "/docs/components/list-header",
    "loading": "/docs/components/loading",
    "menu": "/docs/components/menu",
    "menu-button": "/docs/components/menu-button",
    "menu-toggle": "/docs/components/menu-toggle",
    "modal": "/docs/components/modal",
    "nav": "/docs/components/nav",
    "nav-pop": "/docs/components/nav-pop",
    "nav-push": "/docs/components/nav-push",
    "nav-set-root": "/docs/components/nav-set-root",
    "note": "/docs/components/note",
    "picker": "/docs/components/picker",
    "picker-column": "/docs/components/picker-column",
    "popover": "/docs/components/popover",
    "radio": "/docs/components/radio",
    "radio-group": "/docs/components/radio-group",
    "range": "/docs/components/range",
    "range-knob": "/docs/components/range-knob",
    "refresher": "/docs/components/refresher",
    "refresher-content": "/docs/components/refresher-content",
    "reorder": "/docs/components/reorder",
    "reorder-group": "/docs/components/reorder-group",
    "ripple-effect": "/docs/components/ripple-effect",
    "route": "/docs/components/route",
    "route-redirect": "/docs/components/route-redirect",
    "router": "/docs/components/router",
    "router-outlet": "/docs/components/router-outlet",
    "row": "/docs/components/row",
    "scroll": "/docs/components/scroll",
    "searchbar": "/docs/components/searchbar",
    "segment": "/docs/components/segment",
    "segment-button": "/docs/components/segment-button",
    "select": "/docs/components/select",
    "select-option": "/docs/components/select-option",
    "select-popover": "/docs/components/select-popover",
    "show-when": "/docs/components/show-when",
    "skeleton-text": "/docs/components/skeleton-text",
    "slide": "/docs/components/slide",
    "slides": "/docs/components/slides",
    "spinner": "/docs/components/spinner",
    "split-pane": "/docs/components/split-pane",
    "status-tap": "/docs/components/status-tap",
    "tab": "/docs/components/tab",
    "tab-button": "/docs/components/tab-button",
    "tabbar": "/docs/components/tabbar",
    "tabs": "/docs/components/tabs",
    "tap-click": "/docs/components/tap-click",
    "text": "/docs/components/text",
    "textarea": "/docs/components/textarea",
    "thumbnail": "/docs/components/thumbnail",
    "title": "/docs/components/title",
    "toast": "/docs/components/toast",
    "toggle": "/docs/components/toggle",
    "toolbar": "/docs/components/toolbar",
    "virtual-scroll": "/docs/components/virtual-scroll"
  },
  'Layout': {
    'Stucture': '/docs/layout/structure',
    'Responsive Grid': '/docs/layout/grid',
    'CSS Utilities': '/docs/layout/css-utilities'
    //    'RTL Support': '/docs/layout/rtl'
  },
  'Theming': {
    'Basics': '/docs/theming/basics',
    'Platform Styles': '/docs/theming/platform-styles',
    'CSS Variables': '/docs/theming/css-variables',
    'Color Generator': '/docs/theming/color-generator',
    'Advanced': '/docs/theming/advanced'
  },
  'Publishing': {
    'Progressive Web App': '/docs/publishing/progressive-web-app',
    'iOS App Store': '/docs/publishing/app-store',
    'Android Play Store': '/docs/publishing/play-store',
    'Electron Desktop App': '/docs/publishing/desktop-app'
  },
  'FAQ': {
    'Glossary': '/docs/faq/glossary',
    'Build Errors': '/docs/faq/build',
    'Runtime Errors': '/docs/faq/runtime',
    'Native Errors': '/docs/faq/native',
    'Developer Tips': '/docs/faq/tips',
    'Changelog': 'https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md'
  },
  'Dev Resources': {
    'Books': '/docs/developer-resources/books',
    'Courses': '/docs/developer-resources/courses',
    'Posts': '/docs/developer-resources/posts',
    'Tools': '/docs/developer-resources/tools',
    'Videos': '/docs/developer-resources/videos',
  }
};

export const outbound = {
  'API Reference': '/docs/api',
  'CLI Reference': '/docs/cli/overview',
  'Native APIs': '/docs/native'
};
