/* tslint:disable:quotemark */

export const nativeMenu = {
  "3D Touch": "/docs/native/three-dee-touch",
  "ABBYY Real-Time Recognition": "/docs/native/abbyy-rtr",
  "Action Sheet": "/docs/native/action-sheet",
  "AdMob Free": "/docs/native/admob-free",
  "AdMob Pro": "/docs/native/admob-pro",
  "AES256": "/docs/native/aes-256",
  "Alipay": "/docs/native/alipay",
  "Android ExoPlayer": "/docs/native/android-exoplayer",
  "Android Fingerprint Auth": "/docs/native/android-fingerprint-auth",
  "Android Full Screen": "/docs/native/android-full-screen",
  "Android Permissions": "/docs/native/android-permissions",
  "Answers": "/docs/native/fabric",
  "App Availability": "/docs/native/app-availability",
  "App Center Analytics": "/docs/native/app-center-analytics",
  "App Center Crashes": "/docs/native/app-center-crashes",
  "App Center Push": "/docs/native/app-center-push",
  "App Minimize": "/docs/native/app-minimize",
  "App Preferences": "/docs/native/app-preferences",
  "App Rate": "/docs/native/app-rate",
  "App Update": "/docs/native/app-update",
  "App Version": "/docs/native/app-version",
  "Apple Pay": "/docs/native/apple-pay",
  "Apple Wallet": "/docs/native/apple-wallet",
  "Appodeal": "/docs/native/appodeal",
  "Appsflyer": "/docs/native/appsflyer",
  "Autostart": "/docs/native/autostart",
  "Background Fetch": "/docs/native/background-fetch",
  "Background Geolocation": "/docs/native/background-geolocation",
  "Background Mode": "/docs/native/background-mode",
  "Backlight": "/docs/native/backlight",
  "Badge": "/docs/native/badge",
  "Barcode Scanner": "/docs/native/barcode-scanner",
  "Base64": "/docs/native/base64",
  "Base64 To Gallery": "/docs/native/base64-to-gallery",
  "Battery Status": "/docs/native/battery-status",
  "BLE": "/docs/native/ble",
  "BlinkUp": "/docs/native/blinkup",
  "Bluetooth Serial": "/docs/native/bluetooth-serial",
  "BluetoothLE": "/docs/native/bluetooth-le",
  "Braintree": "/docs/native/braintree",
  "BranchIo": "/docs/native/branch-io",
  "Brightness": "/docs/native/brightness",
  "Broadcaster": "/docs/native/broadcaster",
  "Browser Tab": "/docs/native/browser-tab",
  "Calendar": "/docs/native/calendar",
  "Call Directory": "/docs/native/call-directory",
  "Call Log": "/docs/native/call-log",
  "Call Number": "/docs/native/call-number",
  "Camera": "/docs/native/camera",
  "Camera Preview": "/docs/native/camera-preview",
  "Card IO": "/docs/native/card-io",
  "Chooser": "/docs/native/chooser",
  "Class Kit": "/docs/native/class-kit",
  "CleverTap": "/docs/native/clevertap",
  "Clipboard": "/docs/native/clipboard",
  "Cloud Settings": "/docs/native/cloud-settings",
  "Code Push": "/docs/native/code-push",
  "Contacts": "/docs/native/contacts",
  "Couchbase Lite": "/docs/native/couchbase-lite",
  "Crop": "/docs/native/crop",
  "Date Picker": "/docs/native/date-picker",
  "DB Meter": "/docs/native/db-meter",
  "Deeplinks": "/docs/native/deeplinks",
  "Device": "/docs/native/device",
  "Device Accounts": "/docs/native/device-accounts",
  "Device Feedback": "/docs/native/device-feedback",
  "Device Motion": "/docs/native/device-motion",
  "Device Orientation": "/docs/native/device-orientation",
  "Diagnostic": "/docs/native/diagnostic",
  "Dialogs": "/docs/native/dialogs",
  "DNS": "/docs/native/dns",
  "Document Viewer": "/docs/native/document-viewer",
  "Email Composer": "/docs/native/email-composer",
  "Estimote Beacons\n": "/docs/native/estimote-beacons",
  "Extended Device Information": "/docs/native/extended-device-information",
  "Facebook": "/docs/native/facebook",
  "FCM": "/docs/native/fcm",
  "File": "/docs/native/file",
  "File Chooser": "/docs/native/file-chooser",
  "File Encryption": "/docs/native/file-encryption",
  "File Opener": "/docs/native/file-opener",
  "File Path": "/docs/native/file-path",
  "File Transfer\n": "/docs/native/file-transfer",
  "Fingerprint AIO": "/docs/native/fingerprint-aio",
  "Firebase": "/docs/native/firebase",
  "Firebase Analytics": "/docs/native/firebase-analytics",
  "Firebase Config": "/docs/native/firebase-config",
  "Firebase Dynamic Links": "/docs/native/firebase-dynamic-links",
  "Firebase Messaging": "/docs/native/firebase-messaging",
  "Flashlight": "/docs/native/flashlight",
  "Flurry Analytics": "/docs/native/flurry-analytics",
  "FTP": "/docs/native/ftp",
  "Geofence": "/docs/native/geofence",
  "Geolocation": "/docs/native/geolocation",
  "Globalization": "/docs/native/globalization",
  "Google Analytics": "/docs/native/google-analytics",
  "Google Maps": "https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/README.md",
  "Google Nearby": "/docs/native/google-nearby",
  "Google Play Games Services": "/docs/native/google-play-games-services",
  "Google Plus": "/docs/native/google-plus",
  "Gyroscope": "/docs/native/gyroscope",
  "hce": "/docs/native/hce",
  "Header Color": "/docs/native/header-color",
  "Health": "/docs/native/health",
  "Health Kit": "/docs/native/health-kit",
  "Hot Code Push": "/docs/native/hot-code-push",
  "Hotspot": "/docs/native/hotspot",
  "HTTP": "/docs/native/http",
  "Httpd": "/docs/native/httpd",
  "HyperTrack": "/docs/native/hyper-track",
  "IBeacon": "/docs/native/ibeacon",
  "Image Picker": "/docs/native/image-picker",
  "Image Resizer": "/docs/native/image-resizer",
  "In App Browser": "/docs/native/in-app-browser",
  "In App Purchase": "/docs/native/in-app-purchase",
  "In App Purchase 2": "/docs/native/in-app-purchase-2",
  "In App Review": "/docs/native/in-app-review",
  "Index App Content": "/docs/native/index-app-content",
  "Insomnia": "/docs/native/insomnia",
  "Instagram": "/docs/native/instagram",
  "Intel Security": "/docs/native/intel-security",
  "Intercom": "/docs/native/intercom",
  "Ionic Webview": "/docs/native/ionic-webview",
  "iOS DocumentPicker": "/docs/native/document-picker",
  "iOS File Picker": "/docs/native/file-picker",
  "Is Debug": "/docs/native/is-debug",
  "jAnalytics": "/docs/native/janalytics",
  "Jins Meme": "/docs/native/jins-meme",
  "Keyboard": "/docs/native/keyboard",
  "Keychain": "/docs/native/keychain",
  "Keychain Touch Id": "/docs/native/keychain-touch-id",
  "Launch Navigator": "/docs/native/launch-navigator",
  "Launch Review": "/docs/native/launch-review",
  "LinkedIn": "/docs/native/linkedin",
  "Local Notifications": "/docs/native/local-notifications",
  "Location Accuracy": "/docs/native/location-accuracy",
  "Market": "/docs/native/market",
  "Media": "/docs/native/media",
  "Media Capture": "/docs/native/media-capture",
  "Mixpanel": "/docs/native/mixpanel",
  "Mobile Accessibility": "/docs/native/mobile-accessibility",
  "MS ADAL": "/docs/native/ms-adal",
  "Music Controls": "/docs/native/music-controls",
  "Native Audio": "/docs/native/native-audio",
  "Native Geocoder": "/docs/native/native-geocoder",
  "Native Keyboard": "/docs/native/native-keyboard",
  "Native Page Transitions": "/docs/native/native-page-transitions",
  "Native Ringtones": "/docs/native/native-ringtones",
  "Native Storage": "/docs/native/native-storage",
  "Navigation Bar": "/docs/native/navigation-bar",
  "Network": "/docs/native/network",
  "Network Interface": "/docs/native/network-interface",
  "NFC": "/docs/native/nfc",
  "OneSignal": "/docs/native/onesignal",
  "Open Native Settings": "/docs/native/open-native-settings",
  "OpenALPR": "/docs/native/openalpr",
  "Overview": "/docs/native",
  "PayPal": "/docs/native/paypal",
  "Pedometer": "/docs/native/pedometer",
  "Phonegap Local Notification": "/docs/native/phonegap-local-notification",
  "Photo Library": "/docs/native/photo-library",
  "Photo Viewer": "/docs/native/photo-viewer",
  "Pin Check": "/docs/native/pin-check",
  "Pin Dialog": "/docs/native/pin-dialog",
  "Pinterest": "/docs/native/pinterest",
  "Power Management": "/docs/native/power-management",
  "Printer": "/docs/native/printer",
  "Pro": "/docs/native/pro",
  "Push": "/docs/native/push",
  "QQSDK": "/docs/native/qqsdk",
  "QR Scanner": "/docs/native/qr-scanner",
  "Regula Document Reader": "/docs/native/regula-document-reader",
  "Rollbar": "/docs/native/rollbar",
  "Safari View Controller": "/docs/native/safari-view-controller",
  "Screen Orientation": "/docs/native/screen-orientation",
  "Screenshot": "/docs/native/screenshot",
  "Secure Storage": "/docs/native/secure-storage",
  "Sensors": "/docs/native/sensors",
  "Serial": "/docs/native/serial",
  "Shake": "/docs/native/shake",
  "Sim": "/docs/native/sim",
  "Siri Shortcuts": "/docs/native/siri-shortcuts",
  "SMS": "/docs/native/sms",
  "Social Sharing": "/docs/native/social-sharing",
  "Speech Recognition": "/docs/native/speech-recognition",
  "SpeechKit": "/docs/native/speechkit",
  "Spinner Dialog": "/docs/native/spinner-dialog",
  "Splash Screen": "/docs/native/splash-screen",
  "SQLite\n": "/docs/native/sqlite",
  "Sqlite Db Copy": "/docs/native/sqlite-db-copy",
  "SQLite Porter": "/docs/native/sqlite-porter",
  "StarPRNT": "/docs/native/star-prnt",
  "Status Bar": "/docs/native/status-bar",
  "Stepcounter": "/docs/native/stepcounter",
  "Streaming Media": "/docs/native/streaming-media",
  "Stripe": "/docs/native/stripe",
  "Taptic Engine": "/docs/native/taptic-engine",
  "Tealium": "/docs/native/tealium",
  "TealiumAdIdentifier": "/docs/native/tealium-adidentifier",
  "TealiumInstallReferrer": "/docs/native/tealium-installreferrer",
  "Text To Speech": "/docs/native/text-to-speech",
  "Themeable Browser": "/docs/native/themeable-browser",
  "Toast": "/docs/native/toast",
  "Touch ID": "/docs/native/touch-id",
  "Twitter Connect": "/docs/native/twitter-connect",
  "Uid": "/docs/native/uid",
  "Unique Device ID": "/docs/native/unique-device-id",
  "Uptime": "/docs/native/uptime",
  "User Agent": "/docs/native/user-agent",
  "Vibration": "/docs/native/vibration",
  "Video Capture Plus": "/docs/native/video-capture-plus",
  "Video Editor": "/docs/native/video-editor",
  "Video Player": "/docs/native/video-player",
  "Web Intent": "/docs/native/web-intent",
  "Web Server": "/docs/native/web-server",
  "Webengage": "/docs/native/webengage",
  "Wechat": "/docs/native/wechat",
  "WheelSelector Plugin": "/docs/native/wheel-selector",
  "Youtube Video Player": "/docs/native/youtube-video-player",
  "ZBar": "/docs/native/zbar",
  "Zeroconf": "/docs/native/zeroconf",
  "Zip": "/docs/native/zip"
};
