export default () => <docs-nav items={items}/>;

const items = {
  'Components': {
    'Action Sheet': '/docs/components/action-sheet',
    'Alert': '/docs/components/alert',
    'Badge': '/docs/components/badge',
    'Button': '/docs/components/button',
    'Card': '/docs/components/card',
    'Chip': '/docs/components/chip',
    'Checkbox': '/docs/components/checkbox',
    'Content / Structure': '/docs/components/content-structure',
    'Date Time': '/docs/components/date-time',
    'FAB': '/docs/components/fab',
    'Grid': '/docs/components/grid',
    'Infinite Scroll': '/docs/components/infinite-scroll',
    'Icons': '/docs/components/icons',
    'Inputs': '/docs/components/inputs',
    'Items': '/docs/components/items',
    'Lists': '/docs/components/lists',
    'Loading': '/docs/components/loading',
    'Media': '/docs/components/media',
    'Menu': '/docs/components/menu',
    'Modal': '/docs/components/modal',
    'Navigation': '/docs/components/navigation',
    'Picker': '/docs/components/picker',
    'Popover': '/docs/components/popover',
    'Progress Indicators': '/docs/components/progress-indicators',
    'Radio': '/docs/components/radio',
    'Range': '/docs/components/range',
    'Refresher': '/docs/components/refresher',
    'Reorder': '/docs/components/reorder',
    'Routing': '/docs/components/routing',
    'Searchbar': '/docs/components/searchbar',
    'Skeleton': '/docs/components/skeleton',
    'Spinner': '/docs/components/spinner',
    'Segment': '/docs/components/segment',
    'Select': '/docs/components/select',
    'Slides': '/docs/components/slides',
    'Tabs': '/docs/components/tabs',
    'Toast': '/docs/components/toast',
    'Toggle': '/docs/components/toggle',
    'Toolbar': '/docs/components/toolbar',
    'Typography': '/docs/components/typography'
  }
};
